DROP TABLE IF EXISTS pug;

CREATE TABLE pug (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  age INTEGER NOT NULL,
  home TEXT NOT NULL,
  puppy_dinner TIMESTAMP NOT NULL,
  description TEXT NOT NULL,
  image TEXT NOT NULL
);